### ISSUE TITLE
If kodi is switched off and pimatic restarted, pimatic gets in undefined state

### ISSUE THREAD

**Issue by roelandbraam** [Fjuxx/pimatic-kodi#2]
21:01:43.956 [pimatic-kodi] info: Kodi Disconnected
21:01:43.962 [pimatic-kodi] info: Kodi Disconnected
21:01:44.038 [pimatic] error: A uncaught exception occured: Error: JSON parse error: Error: Unexpected end
21:01:44.038 [pimatic] error:>Line: 1
21:01:44.038 [pimatic] error:>Column: 0
21:01:44.038 [pimatic] error:>Char: 
21:01:44.038 [pimatic] error:>    at Object.onerror (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/lib/TCPConnection.js:186:17)
21:01:44.038 [pimatic] error:>    at emit (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:285:37)
21:01:44.038 [pimatic] error:>    at error (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:320:5)
21:01:44.038 [pimatic] error:>    at end (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:326:7)
21:01:44.038 [pimatic] error:>    at Object.write (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:341:32)
21:01:44.038 [pimatic] error:>    at Object.CParser.close (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:148:42)
21:01:44.038 [pimatic] error:>    at Connection.onClose (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/lib/TCPConnection.js:162:26)
21:01:44.038 [pimatic] error:>    at Socket.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/lib/TCPConnection.js:4:59)
21:01:44.038 [pimatic] error:>    at Socket.EventEmitter.emit (events.js:95:17)
21:01:44.038 [pimatic] error:>    at TCP.close (net.js:466:12)
21:01:44.038 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
21:01:44.049 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
21:01:44.070 [pimatic-kodi] info: Kodi Disconnected
21:01:44.076 [pimatic-kodi] info: Kodi Disconnected
21:01:44.119 [pimatic] error: A uncaught exception occured: Error: JSON parse error: Error: Unexpected end
21:01:44.119 [pimatic] error:>Line: 1
21:01:44.119 [pimatic] error:>Column: 0
21:01:44.119 [pimatic] error:>Char: 
21:01:44.119 [pimatic] error:>    at Object.onerror (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/lib/TCPConnection.js:186:17)
21:01:44.119 [pimatic] error:>    at emit (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:285:37)
21:01:44.119 [pimatic] error:>    at error (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:320:5)
21:01:44.119 [pimatic] error:>    at end (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:326:7)
21:01:44.119 [pimatic] error:>    at Object.write (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:341:32)
21:01:44.119 [pimatic] error:>    at Object.CParser.close (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:148:42)
21:01:44.119 [pimatic] error:>    at Connection.onClose (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/lib/TCPConnection.js:162:26)
21:01:44.119 [pimatic] error:>    at Socket.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/lib/TCPConnection.js:4:59)
21:01:44.119 [pimatic] error:>    at Socket.EventEmitter.emit (events.js:95:17)
21:01:44.119 [pimatic] error:>    at TCP.close (net.js:466:12)
21:01:44.119 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
21:01:44.129 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!

if kodi is running everything seems to be fine, but in my case the default state of kodi is off.

**Comment by Fjuxx** [comment]
Will check asap, thank you for testing.

Does the same thing happen if Kodi gets disconnected after pimatic has been started?

**Comment by roelandbraam** [comment]
Hi,

Nope if pimatic is running everything seems to work fine. Only when restarting pimatic because of config change i get this error.

**Comment by Fjuxx** [comment]
Hi,

i've made an update, Can you test it again.
It seemed to be in the underling library for Kodi/XBMC

**Comment by roelandbraam** [comment]
Hi Fjuxx,

I tested the 0.4 version and i have the following comments:

If i define more then one kodi (i have 3 instances in total) it doesn't work at all, even when kodi is started before pimatic.

If i define only one kodi it works , and i don't get the error message about the defined state, however if i shutdown kodi and start it  again (next day) the plugin doe not work anymore and shows the status of last time kodi was active (it still show that a tv show is active while something else is playing)

It somehow does not reconnect again after it was disconnected from kodi, i can see in the log files that the plugin disconnects from kodi (info [pimatic-kodi]: Kodi Disconnected) but i can't see a connect message after that.  Once in disconnected state it remains that state until pimatic is restarted and i think kodi needs to be online for this. If kodi is offline , no error message appears like before but the plugin will be unusable.

For the meanwhile i'm using python scripts i.c.w shell-execute to interface with xbmc. 

Cheers!

**Comment by roelandbraam** [comment]
Owh i'm also using the pimatic-mpd plugin, and it has the same problem.
Since you used it for creating the kodi plugin, the disconnect problems comes with it :-(

The pimatic-mpd plugin doe not handle disconnects and reconnects properly, the code should be modified to include some checks if mpd is available it should reconnect again.

**Comment by Fjuxx** [comment]
@roelandbraam 
Just made an update that should fix the connection issues.

But for the mutliple Kodi players, could you test it again for me.
And if it does not work send me a debug log?

I do not (yet) have multiple Kodi's running. So hard to test.

**Comment by roelandbraam** [comment]
Hi Fjuxx,

Just tested it when both kodi's were switched off. I noticed a vey high load when starting pimatic daemon and it never finishes starting. It's stuck now and the pimatic-daemon log files says:

11:27:14.322 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:14.334 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:14.347 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:14.360 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.059 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.075 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.102 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.115 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.255 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.300 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.332 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.345 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.357 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.370 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.383 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.395 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.456 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.468 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.482 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.494 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.506 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.518 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.531 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.543 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.556 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.568 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.581 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.593 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.705 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.718 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.731 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.743 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.756 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.769 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.782 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.794 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.807 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.819 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.832 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:27.844 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.144 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.158 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.188 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.201 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.214 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.227 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.241 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.254 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.266 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.279 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.291 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.303 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.316 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
11:27:28.329 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect

Looks like it's to busy reconnecting, as it keeps doing this multiple times for each second. 
Maybe if you reduce reconnect time to check once a minute pimatic will be able to start and won't do 97% cpu time.

I did not check what happens when kodi is up, but i assume that if it's connected this reconnecting issue is not occurring.

regards,
R

**Comment by Fjuxx** [comment]
Please make sure you have the latest version. 0.0.7

this was a problem with my first attempt, now it will only reconnect every 60 sec.

**Comment by roelandbraam** [comment]
It does work now for only 1 kodi configuration, but with  two kodi instances configured the same issue occurs again.

I'm using 0.0.7 version and when only 1 kodi is defined in config.json everything works fine and the reconnect occurs only one time a minute. But if i define a second kodi in the config and both kodi instances are turned off, the plugin tries to reconnect multiple time in a second again.

--> here some log after starting pimatic
12:20:31.407 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.464 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.477 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.490 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.502 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.514 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.526 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.537 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.550 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.634 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.646 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.658 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.670 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.682 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.694 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.706 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.719 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.732 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.744 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.756 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.768 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.780 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.792 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.804 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.816 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:31.987 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.000 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.012 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.024 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.036 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.050 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.062 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.073 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.085 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.097 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.109 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.121 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.133 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.145 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.157 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.169 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.181 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.192 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.204 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.216 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.229 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.241 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.252 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.264 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.276 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.288 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.301 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.313 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.325 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.337 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.349 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.361 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.602 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.615 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.630 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.642 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.654 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.666 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.678 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.690 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.702 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.714 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.726 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.739 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.895 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.907 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.919 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.931 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.943 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.955 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.967 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.980 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:32.992 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.004 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.016 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.028 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.040 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.053 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.065 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.077 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.089 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.101 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.113 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.125 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.302 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.315 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.327 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.340 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.352 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.364 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.376 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.387 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.399 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.411 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.423 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.435 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.447 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.459 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.471 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.484 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.496 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.508 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.520 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.532 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.544 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.556 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.567 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.579 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.716 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.728 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.740 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.752 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.764 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.776 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.788 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.800 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.812 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.824 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.836 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.848 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.860 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.872 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.885 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.897 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.910 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.922 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.934 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.946 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.958 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.970 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.982 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:33.994 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.446 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.459 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.471 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.486 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.498 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.510 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.522 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.534 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.546 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.558 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.570 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.583 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.595 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.607 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.619 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.633 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.645 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.657 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.669 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.681 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.693 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.705 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.717 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.730 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.741 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.753 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.765 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.778 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.790 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.802 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.814 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.826 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.838 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.850 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.862 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.874 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.886 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.898 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.911 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.923 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.935 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.946 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.958 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.970 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.983 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:34.995 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:35.006 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:35.018 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:35.772 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:35.785 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:35.815 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:35.828 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:36.083 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:36.096 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.297 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.315 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.390 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.404 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.434 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.447 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.482 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.494 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.506 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.519 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.620 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.633 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.666 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.679 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.691 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.703 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.715 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.727 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.740 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.752 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.764 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.776 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.789 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.803 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.815 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:37.827 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:38.798 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:38.814 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:38.846 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:38.858 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:40.292 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:40.309 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:40.342 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:40.354 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:40.388 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:40.401 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:40.413 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:40.425 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:40.473 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:40.486 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:40.498 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:40.510 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:41.770 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:41.783 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:41.814 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:41.827 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:43.292 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:43.307 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:43.341 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:43.354 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:46.286 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:46.301 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:46.333 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
12:20:46.345 [pimatic-kodi] info: Kodi Disconnected, Attempting reconnect
