### ISSUE TITLE
Transfer npm ownship

### ISSUE THREAD

**Issue by sweetpi** [Fjuxx/pimatic-kodi#9]
@Fjuxx Could you add me as a npm package owner, so that I can publish the fixed version?

 https://docs.npmjs.com/cli/owner

You need to run the following command for all your packages:

```
npm owner add sweetpi pimatic-kodi
```

**Comment by Fjuxx** [comment]
Done, you already have acces to the git repository correct?

**Comment by sweetpi** [comment]
@Fjuxx Yes, big thanks!
